name: My test site
favicon: null
layout_spectrum: 0.8573728546034545
typography_spectrum: 0.6511961037758738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3257863107137382
  lightness: 0.07081823144108057
  saturation: 0.11234653298743069
  rhythmicContrast: 0.7209525150246918
purpose: []
